# Generated by Django 4.0.2 on 2022-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_resultmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
