# Generated by Django 4.0.2 on 2022-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_quesmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
