# Generated by Django 4.0.2 on 2022-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_resultmodel_date_resultmodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='time',
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
