# Generated by Django 4.0.2 on 2022-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_remove_resultmodel_time_alter_resultmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='date',
            field=models.DateTimeField(verbose_name='dateTime'),
        ),
    ]
