# Generated by Django 4.0.2 on 2022-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_resultmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='dateTime'),
        ),
    ]
