# Generated by Django 4.0.2 on 2022-03-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_alter_resultmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='date',
        ),
    ]
