# Generated by Django 4.0.2 on 2022-03-30 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_remove_resultmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
